"""Generate exact MCP signatures from the live official and Skill registries."""

from __future__ import annotations

import argparse
import inspect
from pathlib import Path
import typing

from tool_registry import build_registry


def _signature(function) -> str:
    hints = typing.get_type_hints(function)
    signature = inspect.signature(function)
    parameters = [
        parameter.replace(annotation=hints.get(parameter.name, parameter.annotation))
        for parameter in signature.parameters.values()
    ]
    return str(signature.replace(parameters=parameters))


def render_reference() -> str:
    registry = build_registry()
    groups = [
        (
            "Official toolkit tools",
            {name: spec.function for name, spec in registry.items() if spec.group == "official"},
        ),
        (
            "Skill remote tools",
            {name: spec.function for name, spec in registry.items() if spec.group == "remote"},
        ),
        (
            "Skill extended tools",
            {name: spec.function for name, spec in registry.items() if spec.group == "extended"},
        ),
    ]
    lines = [
        "# Generated MCP Signatures",
        "",
        "> Generated by `scripts/generate_tool_reference.py` from the live registries. Do not hand-edit.",
        "> Read [toolkit-tools.md](toolkit-tools.md) for routing, policy, and failure handling.",
        "",
    ]
    for title, tools in groups:
        lines.extend([f"## {title}", ""])
        for name, function in tools.items():
            lines.extend(
                [
                    f"### `{name}{_signature(function)}`",
                    "",
                    inspect.getdoc(function) or "No public docstring.",
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    content = render_reference()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"Wrote {args.output} ({len(content)} characters)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
